### ISSUE TITLE
Programming the CV2MIDI

### ISSUE THREAD

**Issue by KonstantineF** [mxmxmx/CV2Midi#3]
Hi @mxmxmx I PMed you on MW about this module, but I decided to post a few ideas about it here as well. How about the following:

1) Utilize the microUSB by creating a small browser-based program to set up the CV2MIDI without using the learn function
2) Allow for a channel to become a CC controller entirely. With two CV inputs and a Gate input you could have three CC controllers (one of which would be an On/Off type). Could be utilized with the learn function as well I guess.

If you turn velocity to 0 "this will essentially silence the channel as far as note-on messages are concerned, ie only make it output CC". Maybe then you could assign three CC messages consecutively, one for each input? Just an idea that will expand on the module's usefulness.

3) An issue I've seen so far. If you set up a channel to be CC instead of Velocity, then you have to do a reset to the module to get it back to Velocity. Unless I'm mistaken, I haven't figured out how to do it in another way.

**Comment by mxmxmx** [comment]
@KonstantineF,  thanks for the suggestions. 

re 1), i'm a bit reluctant to do much in terms of usb, it's on the back of the module so will either be inconvenient or require some surgery to your rack/case (ie drilling a hole, adding a feed-through usb socket). what should be feasible though is dumping the channel configuration via sysex. i'm not much of a web developer though, so it remains to be seen how neat that'll turn out.

re 2), makes sense to me. i guess at least the two signals could be mixed/added to make one CC message (rather than note + CC). not sure how this might work out in terms of the UI though (there's just one switch). 

re 3), right, you have to reset to defaults (as is, that's done by long-pressing the learn button). the more user-friendly solution at any rate should be the sysex dump. that said, the code being open-source, adjusting what the channels do is fairly easy; an interim solution might be to add some more explicit .config file to the source

**Comment by KonstantineF** [comment]
Hello @mxmxmx  thanks for taking the time to reply,

1) Since this is mostly a set-and-forget thing, I doubt it would be an issue to remove a 10hp module in order to plug a USB cable, program it and then screw it back in. It's more or less the same principle as sending SYSex, with the difference of making it easier for the user to actually program the module. My suggestion for browser is to cater to Windows/Mac/Linux differences. If not possible, a Java app would also do the trick. Just a suggestion to keep in mind - somebody else could be interested in providing this. Wish I could do it myself, but alas, it's out of my capabilities. I could try to make a wireframe for the UI though, if that would help you.

2) Two would be better than one, yes. Three even better. Here's a UX suggestion I hinted to in my previous post:

"_When listening to incoming midi messages, the module will adjust [...] midi channel and CC control numbers (0-127) (if receiving CC messages)._"

-  Enter learn mode.
-  Select a channel.
-  Double click to arm the channel.
-  Set channel's velocity level to 0 via knob. That will let the channel know that it should expect 3 CC messages to assign to each CV input for that channel instead of Pitch and/or CC.
-  Send three CC messages. First CC message is assigned to Pitch input, second to Gate (only 0 and 127 values available) input, third to CC/Velocity input.
-  Exit/save via long-press (with current UX).

3) Agreed. I'm unsure how interested you are in making this easier for the user - for all I know I might be the only person interested in this module that can't actually code, so I'm unsure how much time you want to spend to "open it up" to us laymen. That being said, here's another UX idea you might consider:

- channel select: pressing the learn button will cycle through the 5 channels
- arm channel: double-click. the channel LED will start flashing and listen to incoming midi messages.
- exit/save: double-click on an armed channel.
- reset channel: long press on an armed channel.  
- reset all channels: long press in normal mode.

This suggestion loses the ability to disarm a channel without saving, but it adds the option to reset a single channel without having to reset everything. Again, as always, just a suggestion. Let me know what you think :)

**Comment by mxmxmx** [comment]
thanks again.

re 1) once you have access to the usb, one might as well simply update the firmware with the channel configurations hard-coded. we'll see, there's something called the Web Midi API, so whipping up some browser-based sysex thing might not be too much work.

re 2, 3) i'll think about it. there should be a way to reset just a single channel, not all of them, depending on context. the 3 x CC thing is more tricky, i was considering using the pots as additional UI, but they're offsets to the CV inputs, so that's kind of inviting user errors (like when something is patched to the velocity inputs). also, as is, the thing is strictly sample+hold; could be changed, of course, but sending midi continuously / assigning stuff to the trigger and CV independently isn't part of the current scheme.

**Comment by KonstantineF** [comment]
1) Thanks for considering it.

2), 3) I see your point. I didn't consider that the main reason for this was to replace Velocity with Volume. That explains why a S&H is used in both areas. In that case, yes, discard my suggestion. 

You could assign two CC messages, one in Velocity input and one in Pitch input and only grab their values when a Gate is present. That seems more logical, given the design. 

4) Would it be possible to learn the power requirements for the module?

**Comment by mxmxmx** [comment]
2 
yeah, two CC messages should work, somehow. definitely it'll work with usb/config settings or sysex dump or something analogous. in theory, the thing can be clocked up to audio rates, so quasi-midi-LFOs etc should be possible even now; question is at which point things will choke / if i'll have to add some rate-limiter.

4 
i haven't measured it yet, i'd guesstimate somewhere ~ 50mA @12V

**Comment by KonstantineF** [comment]
After some consideration an explicit config file would also do the trick. It should be fairly easy to reload the code to the Teensy with any changes made on the config file to set the module as desired. It also saves you from a lot of addition, and probably unnecessary work. It also sounds like a better idea to Sysex or spending the time with a Web Application.

The question is, will this require that the user recalibrates the module every time? I doubt it, but it's worth asking.

Parameters I can come up with, for the config file:
- MIDI channel (is that per track?)
- Choose between Pitch or CC message per track
- Choose between Velocity or CC message per track
- A/B TRS-MIDI mapping, unless that's done on the hardware side.

**Comment by mxmxmx** [comment]
yeah, that's probably the least-effort version. it won't need recalibration, the calibration is simply about 'zero'-values, that is offset variations at the CV inputs. except for the choice of A/B type (there's two switches on the back of the module, ie hardware), all those parameters would work.

**Comment by KonstantineF** [comment]
May I also ask, what is the ranges of the CV inputs? 0-5V ?

**Comment by mxmxmx** [comment]
if following the BOM, the range will end up -5V/+5V for the pitch inputs, the velocity input is also 10VPP,  offset depends on the pot.

**Comment by KonstantineF** [comment]
My apologies if my questions seem ignorant at times. 

-5 to +5V sounds like a 10 octaves range. One question would be, can it be pushed/modified to do 0 to 10V? I presume the answer is no as the range is set on the hardware side. Correct?

I'm curious as to your decision to go for -5V/+5V instead of 0-10V which would seem more reasonable since these this is pitch-related CV. 

As always, thank you for taking the time to answer and clarify some points of the project.

**Comment by mxmxmx** [comment]
the range is a hardware thing, but the offset can be modified easily (just requires using different resistor values). i went for -5V/+5V because in parts it's intended for basic S+H applications (using LFOs and the like); and five octaves are typically enough for sequencer stuff.

**Comment by KonstantineF** [comment]
Do the knobs controlling velocity act as attenuators for the incoming CV value when a jack is plugged?

**Comment by mxmxmx** [comment]
no, they're offsets. you'll need an external attenuator.

**Comment by KonstantineF** [comment]
From my experience with velocity control in Eurorack, attenuation of the incoming CV is the best option as it allows you to dial down the velocity, or at least set the maximum level desirable. Think of it as a limiter of sorts. Especially in the modular world, I would assume that users would most likely plug LFO's, ADSRs, or other fluctuating signals in that jack so I'm not sure if offset is indeed more helpful.

I can see how useful it is when nothing is plugged at the jack. I assume it was more practical for your specific needs, right? 

Is there a workaround by modifying the hardware or the BOM? In any case, maybe something to consider _if_ you ever decide to revise the design. Not a big issue by any means, just sharing some thoughts.

Thank you.

**Comment by mxmxmx** [comment]
i suppose it's a matter of taste, i suppose you pretty much always want both, attenuation and offset; in this case, you probably definitely want both. attenuation is easy, offset not so much.

**Comment by KonstantineF** [comment]
Both is always optimal but I wouldn't request so much out of such a module. Apart from having experience with such a design, my reasoning for supporting attenuation is because it's more practical in a performance situation to be able to mute a voice with no need for external interference. 

In this occasion it seems the velocity input requires a 10V signal to reach 127. So maybe the offset was the better choice after all. 

I'm happy to report that the hex file worked like a charm. First test was positive. I'll try the TRS input for programming tonight.

**Comment by mxmxmx** [comment]
yep, it's 10V. if you prefer, that's something that easily can be made somewhat more sensitive in the software.

and good to hear. the 'learn' stuff should be basically working but there might be some loose ends ...

**Comment by KonstantineF** [comment]
I'm sorry to report that first attempts to program the module via learn button have failed. I've tried using hardware but it doesn't seem to learn the pitch or Midi channel. 

I would also suggest that when a track learns the incoming data, it stops blinking and learn button goes back to toggling between tracks. That way there's a clear indication that the channel has received and learned the data.

Additionaly, it would be helpful that Midi input gets passed through to the output. If not always, at least during learn mode, so that there's a clear indication of the message being sent.

**Comment by mxmxmx** [comment]
can you confirm the input works in principle? the learn mode prints to the serial monitor (of the arduino IDE). to do this safely, make sure you have cut the trace (see [here](https://github.com/mxmxmx/CV2Midi/wiki/build-it#prepare-the-teensy))

we can take it from there; as i said, there's some loose ends.

**Comment by KonstantineF** [comment]
It was my mistake. I had both PCB switches on the same side, which meant that input and output were using different TRS-DIN mappings. 

Input works as advertised AND outputs incoming data when in Learn mode, as requested. Excellent! 

Did some little testing and managed to get to module to be unresponsive to incoming pitch changes. Not sure how, I haven't been ablento replicate the issue, but I will investigate further.

**Comment by mxmxmx** [comment]
ah, good. 

re: being unresponsive -- so the module crashes (never happened to me, but possible)? or it's just that the inputs become unresponsive but it works otherwise? (which would be odd)

either way, ... interesting that it should pass through the data.  i remember i kind of _wanted_ to implement that, but looking at the code it doesn't look like i actually did.

**Comment by KonstantineF** [comment]
It was unresponsive to pitch changes but gate inputs worked just fine. I only plugged a controller CV in all 5 pitch inputs at the same time. I'll see if I can replicate. 

Well, weird that you say it shouldn't work like that because it does!

You should consider my suggestion for the track to stop being in the "ready to learn" status when it has received proper data. It would be a good indication. 

Thanka for everything

**Comment by mxmxmx** [comment]
ok, weird, i'll investigate midi in when i get round to it.

re pitch: the CV inputs are entirely agnostic about physical connections; ie they're sampled at the sample rate continuously, no matter what. what does make a difference (in terms of processing load) is the trigger inputs (because resulting in midi output); seems odd in any case the gates should still be responsive, but not the CV inputs. let me know if you can find a way to replicate ...

**Comment by KonstantineF** [comment]
@mxmxmx I still have problems with the device. I'm trying to program the module to have all tracks by default at Midi channel 1, with C2 at 0V, but it's proving impossible. 

First off I need to send a G#1 in order to have the note be programmed in C2. It doesn't play out the note I program into it.  And the programming gets messed up when I program the other tracks, it loses the previous notes. Turned the case off. I'll return to it again today and try again. Let me know if you want a video.

**Comment by mxmxmx** [comment]
no video necessary. 

can you try this now? https://github.com/mxmxmx/CV2Midi/tree/dev ... there was/is indeed something weird going on with that midi library. it's using the raw/vanilla serial now which seems to fix it. (this also caused the echoing of the incoming notes, which shouldn't have happened, as noted above). 

learn mode now _ intentionally_ echos the incoming midi data (note data and CC), and the "learn" LED will blink when receiving data.

**Comment by KonstantineF** [comment]
Thank you for keeping/implementing echo of the incoming MIDI data. It is very helpful both in practice and for troubleshooting (I'm plugging the output to a MIDI monitor to see what is happening). Additionally, it's a nice idea to have the LED blink when receiving data, that way there's an indication of what is going on.

Let me know if there's a hex file I can use and I'll program the module today and test.

**Comment by mxmxmx** [comment]
yeah, compiling should be easy (see [here](https://github.com/mxmxmx/CV2Midi/wiki/build-it#firmware); there aren't any dependencies on external libraries.

you can set the default note number here (for all channels): https://github.com/mxmxmx/CV2Midi/blob/dev/software/C2M_X/APP_CV2MIDI.ino#L32

i'll move this to C2M_options.h in due course and on a per-channel basis (or track, if you prefer); ditto for default midi channel.

**Comment by mxmxmx** [comment]
ps. you want to try the dev branch, of course, not master

**Comment by mxmxmx** [comment]
pps.
i've moved the default stuff to [CM_options.h](https://github.com/mxmxmx/CV2Midi/blob/dev/software/C2M_X/C2M_options.h).

**Comment by KonstantineF** [comment]
I haven't managed to compile and test yet but will do after upcoming concert. Thanks for providing that CM_options.h file. Am I right to assume that it's part of the compilation? (re: it is required to compile and can't use the hex file if you want to utilize the CM_option.h)

**Comment by mxmxmx** [comment]
right, CM_options.h is part of / compiled into the firmware; that's the hardcoded default values so to speak. fwiw, i've just put up the .hex file [here](https://github.com/mxmxmx/CV2Midi/releases/tag/v1.1). the learn-stuff i think functions properly now.

**Comment by KonstantineF** [comment]
Ok, so what I will do is try the new hex file utilizing the learn-stuff tonight. I need to change the channel and notes on my module anyway (due to setup, not the module's fault) so I'll give it a try that way. After testing that and after Saturday I'll try the CM_options.h and report back if I run into anything weird.

2hp's Play utilizes a simple .txt file for setting up internal parameters, as part of its boot procedure. I'm sure it's a non issue for you, but do consider such an approach as easier to use for others. As always, not a request, just a suggestion for you to consider. You're already v e r y accommodating.

PS: Performing in SuperBooth 19's Koma afterparty with your module by the way, if you're around.

**Comment by mxmxmx** [comment]
ok, let me know how it goes (and feel free to open a new issue if need be, this one got a bit unwieldy)

re .txt file, wouldn't be a big deal ...  it's not possible though w/o a an uSD card or the like, i'm afraid.

and cool, i'll be around for SB, so perhaps see you there.
