### ISSUE TITLE
user manual + .hex

### ISSUE THREAD

**Issue by pppier** [mxmxmx/CV2Midi#6]
hi, 
I'd like to have more info starting from the 3 minijack input (I suggest you to update the infos with clearer in/out naming)
built two, trying to calibrate and check the functions, I don't know what to expect feeding the 3 (I imagine it but having misbehaviour I'd like to start from a clear point)

and is possible to have an .hex file (similar to o_C and TU, so easy to flash...)? I see multiple .ino, not sure about libraries included and so on...

I hope it can help, and not be only my frustration.
(I really appreciate your wonderful modules)

**Comment by mxmxmx** [comment]
hi

see here: https://github.com/mxmxmx/CV2Midi/wiki/usage and let me know if that helps.

there's no hex for this
