### ISSUE TITLE
Programming via Learn Input loses tuning

### ISSUE THREAD

**Issue by KonstantineF** [mxmxmx/CV2Midi#9]
I downloaded the newest firmware and gave it a test run.
Disclaimer:
1) I haven't tried editing the settings file and then compiling. It's too much fuss right now, I went straight to the .hex file applied and reprogrammed the Channel/Note settings via Learn input
2) I did not recalibrate the module

I'm running across the same issue I had with v1.0. I need to program the track (I prefer that term in order to avoid confusion with MIDI channel) to MIDI Note 35 in order to have it play MIDI Note 36. That's just an example.

It's not consistent. If you plug nothing at the CV input and just fire a gate it sometimes fires 36 (most of the times) and sometimes actually fires 35 (which is the note it's been programmed to). So it moves around that semitone distance.

This applies to ALL tracks. Could it be a hardware thing?

It's not a huge issue for me, frankly, as I like my chords to be somewhat messy. A little dissonance didn't hurt anyone. It might be a nice way to have some random element in. But, that being said, it's not consistent, and that might be an issue for you or others. Especially if aim to have the note fire a sample or something.

**Comment by mxmxmx** [comment]
mmh.

i'd first re-calibrate the module and see if that helps, takes 1 minute. (if it jumps in between two notes, it almost sounds as if the offset isn't zeroed, which is what the calibration is about, mainly).

we'll take it from there  ... i've been stress-testing the thing here for the last three days; i think it should work.

**Comment by KonstantineF** [comment]
Yeah, I've been pushing it as well. Seems to be doing fine.
One thing I'd urge you to consider is merging incoming MIDI messages in normal mode. That way you'd be able to use two modules without an external merger. Would that cause too much timing issues?

I'll calibrate the module and try again during next week. 

By the way, I've also noticed that Velocity of a NoteOn is at 2 when knob is fully counterclockwise. Nothing plugged at the Pitch or Velocity input. Is that to be expected?

**Comment by mxmxmx** [comment]
> By the way, I've also noticed that Velocity of a NoteOn is at 2 when knob is fully counterclockwise

no, if properly calibrated, it should be zero. 

re merging: well, it would eat away what limited bandwidth there is. i guess i could try / see how it works; and perhaps add it as a compile option.

**Comment by KonstantineF** [comment]
Thanks for considering it. I'm speaking for myself here, but I do believe it's a useful feature to have, if it works properly.

I'll do the calibration process suggested and see how things work. If I'm not mistaken, and assuming we're both talking about the MI one, it only has to do with pitch, so I'm hard pressed to see how this will work with velocity, unless the module recognizes the voltages and sets all its calibration accordingly. In any case, I'll report back with my results.

Thanks again!

**Comment by mxmxmx** [comment]
>  If I'm not mistaken, and assuming we're both talking about the MI one [...]

 ... we're talking about the calibration for *this* module, not a MI one. as pointed out above, calibration is (among other things) about calibrating the voltage *offsets* at the inputs, so the module knows what "zero" volts is.

**Comment by KonstantineF** [comment]
Apologies. But you are referring to [this](https://github.com/mxmxmx/CV2Midi/wiki/calibration) procedure which is exactly the same as the calibration procedure described [here](https://mutable-instruments.net/modules/clouds/manual/). I, probably wrongfully, assumed that it was based on the MI calibration procedure, in the way the quantization was taken from MI Braid's quantizer.

I can have a three digit precision of the voltage, so I'm hoping it will be good enough for this process.

**Comment by mxmxmx** [comment]
sure, it's similar, it serves similar purposes. nevertheless it hasn't "only ... do with pitch":

- "push the "learn" button to initiate the procedure: the 5 LEDs next to the trigger/gate inputs will light up one by one ( = **calibrating the offsets**)."

the point here is to compensate for any voltage offset at the inputs ( = all the inputs = pitch and velocity inputs), which is something you'll pretty much invariably see, because real physical things are imperfect. it's just to rule out the more obvious things before we worry about hardware or software issues.

**Comment by KonstantineF** [comment]
Fair point. Apologies for my naivete. I saw 1V - 3V and though the process was the same. Your point is very reasonable and I know have a minutely better grasp of what the calibration does behind the scenes.
